### ISSUE TITLE
[Render Quilt] Blender does not render on macOS

### ISSUE THREAD

**Issue by JohJakob** [regcs/AliceLG-beta#9]
**Blender 2.93.1 Release Candidate (5 June 2021)**
**Alice/LG Beta 6**
**macOS 11.4 Big Sur**
**AMD Radeon Pro 560 4 GB**

Blender does not render a quilt using Alice/LG on macOS. When clicking on the “Render Quilt” button, the “Blender Render” window appears as expected, but it just shows an empty image in the “Render Result” slot. The render progress on the “Render Quilt” button and in the status bar stays at 0%. Cancelling the rendering also does not seem to work. I have to force quit Blender in order to stop it.

<img width="551" alt="Screenshot 2021-06-05 at 16 20 04" src="https://user-images.githubusercontent.com/9888537/120894660-e4cc2c00-c619-11eb-94d4-c3bec28151eb.png">

**Comment by regcs** [comment]
Could you test, if the problem persists with that version:
https://github.com/regcs/AliceLG-beta/releases/tag/v1.1.1-beta

If it does, could you please open Blender in console mode, reproduce the bug, and post the output of the terminal? That would help in finding the cause.

**Comment by JohJakob** [comment]
Thanks for your fast reply!
It still does not render. This is the console output:

```
[INFO] Operator state:  INVOKE_RENDER
[INFO] Operator state:  INVOKE_RENDER
[INFO] Invoking new render job.
[INFO] FRAME AND VIEW
[INFO] STORE USER CAMERA SETTINGS
[INFO] CAMERA SETTINGS
[INFO] INVOKE
[ INIT_RENDER ] WAITING
```

`[ INIT_RENDER ] WAITING` is then printed over and over again until I force quit Blender again.

**Comment by regcs** [comment]
Sure, you're welcome. And thanks for the log, unfortunately that doesn't include any obvious errors. Strange ... could you make a screenshot of both the "Looking Glass" Panel and blenders rendering settings after the rendering was started?

**Comment by JohJakob** [comment]
Yes, it’s very strange. That is all I’m seeing after clicking on “Render Quilt”:

<img width="575" alt="Screenshot 2021-06-05 at 17 54 38" src="https://user-images.githubusercontent.com/9888537/120897559-1bf50a00-c627-11eb-98a1-b18887e38e5e.png">

**Comment by regcs** [comment]
Hm. In addition to that, could you also show the "Output Properties" tab of blenders render settings?

And did you try the non-experimental version (2.93.0 LTS)? I just tried to reproduce it there, but could not. Now I am downloading the 2.93.1.

**Comment by JohJakob** [comment]
Sure! Alice/LG uses one camera instead of multiple like Looking Glass Factory’s add-on does at the moment so I think “Stereoscopy” being disabled is correct, right?

<img width="331" alt="Screenshot 2021-06-05 at 18 12 53" src="https://user-images.githubusercontent.com/9888537/120898073-a76f9a80-c629-11eb-81de-973a5c57d244.png">

I was trying to render with Cycles, but switching to Eevee shows the exact same result. The issue is also present in Blender 2.93.0.

**Comment by JohJakob** [comment]
Yes, I used a new scene with a cube, but the issue also occured in existing scenes.

Could it be that this has something to do with the Python libraries that need to be installed?

**Comment by regcs** [comment]
> Sure! Alice/LG uses one camera instead of multiple like Looking Glass Factory’s add-on does at the moment so I think “Stereoscopy” being disabled is correct, right?

That is correct, yeah. 

> I was trying to render with Cycles, but switching to Eevee shows the exact same result. The issue is also present in Blender 2.93.0.

Is this your first attempt to render something with Alice/LG or has there been a Blender version it worked with for you before?

**Comment by regcs** [comment]
> Could it be that this has something to do with the Python libraries that need to be installed?

At the moment, I would not exclude that. Do you have those packages installed or not?

**Comment by JohJakob** [comment]
> Is this your first attempt to render something with Alice/LG or has there been a Blender version it worked with for you before?

Yes, I tried it for the first time a few days ago with Beta 6 and the last Beta versions of Blender 2.93 and Alpha version of Blender 3.0.

> At the moment, I would not exclude that. Do you have those packages installed or not?

Well, I encountered some issues with this as well. In Beta 6, the section containing the “Install” button was present and clicking it installed the libraries (but also threw an error for one library in the console). After installing Beta 7 (install → relaunch Blender → enable add-on → open preference pane), this section is not displayed hence only `hid` and `pynng` appear in the `lib` folder.

**Comment by regcs** [comment]
> Yes, I tried it for the first time a few days ago with Beta 6 and the last Beta versions of Blender 2.93 and Alpha version of Blender 3.0.

Hm, okay, so the issue appeared starting with the final release of 2.93, correct?

> Well, I encountered some issues with this as well. In Beta 6, the section containing the “Install” button was present and clicking it installed the libraries (but also threw an error for one library in the console). 

There was an issue with Beta 6, where this could potentially happen. Maybe that was the case here, but can't say for sure without further testing. But if Beta 7 does not show the "install" button, then all required modules are present. To be sure, you could post the command line output after Blender was initialized.

> After installing Beta 7 (install → relaunch Blender → enable add-on → open preference pane), this section is not displayed hence only `hid` and `pynng` appear in the `lib` folder.

Are you running blenderLKG 3.0+ in parallel? That might explain why the "install" button does not appear for Alice/LG - blenderLKG installs the same libraries in Blender's python library.

**Comment by JohJakob** [comment]
> Hm, okay, so the issue appeared starting with the final release of 2.93, correct?

Yes, that’s correct! I just tried rendering with Blender 2.83.15 and it works like expected.

Here is the console output regarding Alice/LG after launching Blender (2.93):

```
Initializing add-on  Alice/LG-beta v1.1.2
 # Add-on path is: /Users/johjakob/Library/Application Support/Blender/2.93/scripts/addons/AliceLG-beta7
Initializing Holo Play Core:
 # Registering at Holoplay Service as: Alice/LG-beta v1.1.2
 # HoloPlay Service version: 1.2.0
 # HoloPlay Core SDK version: 1.0.0
 # Number of connected displays: 0
########################################################################
Initialized the Looking Glass Addon.
```

> blenderLKG installs the same libraries in Blender's python library.

Ah, I see! Yes, I am running blenderLKG 3.1 Release Candidate 1 in parallel.

**Comment by JohJakob** [comment]
Rendering with Blender 2.92 also works.

**Comment by regcs** [comment]
Ok, the initialization looks also fine.

> Edit: It works with new scenes and both Cycles and Eevee, but I couldn’t get existing scenes to render.

There was one person so far, that reported a similar behavior. He also send me a blend-file, with which I could reproduce the behavior ... but I cannot see any cause. The settings seem to be identical to new .blend-files if I compare them. It is really weird and hard to grasp, what is going on there ...

**Comment by regcs** [comment]
Ok, I think I resolved it. Could you test the new version:

https://github.com/regcs/AliceLG-beta/releases/tag/v1.1.2-beta

**Comment by JohJakob** [comment]
> It is really weird and hard to grasp, what is going on there ...

Yeah, it’s a very strange issue and probably a very specific edge case.

Unfortunately, the new version does not make a difference :(

**Comment by regcs** [comment]
> Unfortunately, the new version does not make a difference :(

Damn. :/ After clicking "Render Quilt", does the camera move?

**Comment by JohJakob** [comment]
No, the camera does not move at all and the console still prints the `[ INIT_RENDER ] WAITING` message. Blender also does not appear to prepare anything for rendering, like building the BVH or loading textures.

**Comment by regcs** [comment]
I don't get it. Just do make sure that everything during the installation went okay, could you please: 

- Navigate to: /Users/johjakob/Library/Application Support/Blender/YOURVERSION/scripts/addons/AliceLG-beta7
(please replace 'YOURVERSION' with the appropriate blender version you installed the new plugin to)

- make a zip from the complete AliceLG-beta7 and sent it to me here

**Comment by JohJakob** [comment]
I’m so sorry for the trouble 😅

Here’s the add-on folder for Blender 2.93. I did a clean install at some point and blenderLKG is not installed at the moment. However, the `lib` folder still only contains two libraries and I was not prompted to install the Python libraries after installing Alice/LG. Does blenderLKG install these in a different place so they are still available even if blenderLKG is gone?

[AliceLG-beta7.zip](https://github.com/regcs/AliceLG-beta/files/6604113/AliceLG-beta7.zip)

**Comment by JohJakob** [comment]
I’m not sure if this is related, but this is the error message thrown when installing the Python libraries:

```
    ERROR: Command errored out with exit status 1:
     command: '/Applications/Blender 3.0 Alpha/Blender.app/Contents/Resources/3.0/python/bin/python3.9' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/6h/jr15dlns681854bjjxb24xtc0000gn/T/pip-install-8lw36_pr/cffi/setup.py'"'"'; __file__='"'"'/private/var/folders/6h/jr15dlns681854bjjxb24xtc0000gn/T/pip-install-8lw36_pr/cffi/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/6h/jr15dlns681854bjjxb24xtc0000gn/T/pip-record-6i5mevsv/install-record.txt --single-version-externally-managed --home /private/var/folders/6h/jr15dlns681854bjjxb24xtc0000gn/T/pip-target-az7canaz --compile --install-headers /private/var/folders/6h/jr15dlns681854bjjxb24xtc0000gn/T/pip-target-az7canaz/include/python/cffi
         cwd: /private/var/folders/6h/jr15dlns681854bjjxb24xtc0000gn/T/pip-install-8lw36_pr/cffi/
    Complete output (36 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.13-x86_64-3.9
    creating build/lib.macosx-10.13-x86_64-3.9/cffi
    copying cffi/backend_ctypes.py -> build/lib.macosx-10.13-x86_64-3.9/cffi
    copying cffi/error.py -> build/lib.macosx-10.13-x86_64-3.9/cffi
    copying cffi/setuptools_ext.py -> build/lib.macosx-10.13-x86_64-3.9/cffi
    copying cffi/__init__.py -> build/lib.macosx-10.13-x86_64-3.9/cffi
    copying cffi/cffi_opcode.py -> build/lib.macosx-10.13-x86_64-3.9/cffi
    copying cffi/vengine_gen.py -> build/lib.macosx-10.13-x86_64-3.9/cffi
    copying cffi/pkgconfig.py -> build/lib.macosx-10.13-x86_64-3.9/cffi
    copying cffi/model.py -> build/lib.macosx-10.13-x86_64-3.9/cffi
    copying cffi/ffiplatform.py -> build/lib.macosx-10.13-x86_64-3.9/cffi
    copying cffi/api.py -> build/lib.macosx-10.13-x86_64-3.9/cffi
    copying cffi/vengine_cpy.py -> build/lib.macosx-10.13-x86_64-3.9/cffi
    copying cffi/commontypes.py -> build/lib.macosx-10.13-x86_64-3.9/cffi
    copying cffi/lock.py -> build/lib.macosx-10.13-x86_64-3.9/cffi
    copying cffi/recompiler.py -> build/lib.macosx-10.13-x86_64-3.9/cffi
    copying cffi/cparser.py -> build/lib.macosx-10.13-x86_64-3.9/cffi
    copying cffi/verifier.py -> build/lib.macosx-10.13-x86_64-3.9/cffi
    copying cffi/_cffi_include.h -> build/lib.macosx-10.13-x86_64-3.9/cffi
    copying cffi/parse_c_type.h -> build/lib.macosx-10.13-x86_64-3.9/cffi
    copying cffi/_embedding.h -> build/lib.macosx-10.13-x86_64-3.9/cffi
    copying cffi/_cffi_errors.h -> build/lib.macosx-10.13-x86_64-3.9/cffi
    running build_ext
    building '_cffi_backend' extension
    creating build/temp.macosx-10.13-x86_64-3.9
    creating build/temp.macosx-10.13-x86_64-3.9/c
    gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -I/Users/sebbas/Developer/Blender/fluid-mantaflow/build_darwin/deps/Release/sqlite/include -I/Users/sebbas/Developer/Blender/fluid-mantaflow/build_darwin/deps/Release/bzip2/include -I/Users/sebbas/Developer/Blender/fluid-mantaflow/build_darwin/deps/Release/lzma/include -I/Users/sebbas/Developer/Blender/fluid-mantaflow/build_darwin/deps/Release/zlib/include -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk -mmacosx-version-min=10.13 -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk -mmacosx-version-min=10.13 -arch x86_64 -DUSE__THREAD -DHAVE_SYNC_SYNCHRONIZE -I/usr/local/Cellar/libffi/3.3_3/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/ffi -I/Applications/Blender 3.0 Alpha/Blender.app/Contents/Resources/3.0/python/include/python3.9 -c c/_cffi_backend.c -o build/temp.macosx-10.13-x86_64-3.9/c/_cffi_backend.o
    c/_cffi_backend.c:2:10: fatal error: 'Python.h' file not found
    #include <Python.h>
             ^~~~~~~~~~
    1 error generated.
    error: command '/usr/bin/gcc' failed with exit code 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: '/Applications/Blender 3.0 Alpha/Blender.app/Contents/Resources/3.0/python/bin/python3.9' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/6h/jr15dlns681854bjjxb24xtc0000gn/T/pip-install-8lw36_pr/cffi/setup.py'"'"'; __file__='"'"'/private/var/folders/6h/jr15dlns681854bjjxb24xtc0000gn/T/pip-install-8lw36_pr/cffi/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/6h/jr15dlns681854bjjxb24xtc0000gn/T/pip-record-6i5mevsv/install-record.txt --single-version-externally-managed --home /private/var/folders/6h/jr15dlns681854bjjxb24xtc0000gn/T/pip-target-az7canaz --compile --install-headers /private/var/folders/6h/jr15dlns681854bjjxb24xtc0000gn/T/pip-target-az7canaz/include/python/cffi Check the logs for full command output.
```

**Comment by regcs** [comment]
> I’m so sorry for the trouble 😅

No worries. ;)

>  Does blenderLKG install these in a different place so they are still available even if blenderLKG is gone?

I think, blenderLKG installs it into the python installation that is bundles with Blender. However, I would expect that if you delete the Blender.app and really make a fresh install, Alice/LG should prompt you for installing the packages. 

Could you also send me one of the .blend files, which don't work for you? Then I can check, if I can reproduce it here.

**Comment by regcs** [comment]
> I’m not sure if this is related, but this is the error message thrown when installing the Python libraries:

That is indeed also strange. So, in Blender 3.0 the "install" button appears in Alice? And what packages are installed in Alice's "lib" folder then?

**Comment by JohJakob** [comment]
Sure!

[Koinobori-Alice.blend.zip](https://github.com/regcs/AliceLG-beta/files/6604237/Koinobori-Alice.blend.zip)

> That is indeed also strange. So, in Blender 3.0 the "install" button appears in Alice? And what packages are installed in Alice's "lib" folder then?

Strangely, the “Install” button appears in Blender 3.0, but after installing, I do not get prompted to restart Blender. It will also still be there after relaunching. These libraries are present in the `lib` folder: `cbor`, `hid`, `pycparser`, `pynng`, and `sniffio`. `install.log` next to them does not show any errors.

**Comment by regcs** [comment]
Thanks for the file. But now the worst case happened: It renders fine on my machine. 😅 

So, let's check the other way around. Attached is my Alice/LG folder directly taken from the blender installation with all libraries installed. Just close Blender, remove your Alice/LG folder, and copy my folder into place. Then start blender and check if it works.

[AliceLG-beta7.zip](https://github.com/regcs/AliceLG-beta/files/6604415/AliceLG-beta7.zip)

**Comment by JohJakob** [comment]
Alright, I replaced the folder with yours. I had to change all tabs in `libHoloPlayCore.py` to spaces because Blender gave me a `TabError` (you may want to use only tabs or spaces to prevent this error) and after trying to enable the add-on again, I had to make `lib/hid/macos/libhidapi.0.dylib` and `lib/pynng/_nng.abi3.so` executable using the `xattr -dr com.apple.quarantine` command because macOS told me that it couldn’t open them.

<img width="372" alt="Screenshot 2021-06-06 at 17 49 13" src="https://user-images.githubusercontent.com/9888537/120931155-b2413280-c6f0-11eb-9123-d9538757af13.png">

I was able to enable the add-on afterwards, but unfortunately, it still does not work.

**Comment by regcs** [comment]
Sorry for the trouble with activating it ... 😣

At the moment I am really out of ideas. If we both use Blender 2.93 with the same blend-file and the same add-on files, I don't see what could cause this problem. Too weird ... :( I will think about it further.

**Comment by JohJakob** [comment]
> Sorry for the trouble with activating it ... 😣

Don’t worry, I was expecting that!

Yeah, it’s really strange. It looks like there’s something very specific on my computer that’s causing this issue. I will investigate further. Maybe cleaning everything up that’s relevant for Blender and doing a fresh install can resolve the issue.

**Comment by regcs** [comment]
> Yeah, it’s really strange. It looks like there’s something very specific on my computer that’s causing this issue. I will investigate further. Maybe cleaning everything up that’s relevant for Blender and doing a fresh install can resolve the issue.

At the moment, I think it is rather Alice that is doing something that Blender does not like. And in most cases we are lucky that it works, but on some machines a special type of configuration might reveal the issue. I also have an idea, what the problem is, but simply don't know how to circumvent it without breaking anything else. Could you test the following:

1. Open Blender and set up everything for rendering with Alice, but don't start rendering. 
2. Go to the "Scripting" workspace and enter this:
```

import bpy
import time


# ------------ QUILT RENDERING -------------
# Modal operator for handling rendering of a quilt out of Blender
class LOOKINGGLASS_OT_render_quilt(bpy.types.Operator):

    bl_idname = "render.quilt"
    bl_label = "Render"
    bl_description = "Render a quilt (animation) using the current scene and active camera."
    bl_options = {'REGISTER'}

    # OPERATOR STATE
    # this is used for handling different rendering steps
    operator_state: bpy.props.EnumProperty(items = [
                                                    ('INVOKE_RENDER', '', ''),
                                                    ('INIT_RENDER', '', ''),
                                                    ('PRE_RENDER', '', ''),
                                                    ('POST_RENDER', '', ''),
                                                    ('COMPLETE_RENDER', '', ''),
                                                    ('CANCEL_RENDER', '', ''),
                                                    ('IDLE', '', '')
                                                    ],
                                            default='INVOKE_RENDER'
                                            )

    # event and app handler ids
    _handle_event_timer = None	# modal timer event

    def init_render(self, Scene, unknown_param):

        # reset the operator state to IDLE
        if self.operator_state != "CANCEL_RENDER": self.operator_state = "INIT_RENDER"

    # function that is called before rendering starts
    def pre_render(self, Scene, unknown_param):

        # reset the operator state to PRE_RENDER
        if self.operator_state != "CANCEL_RENDER": self.operator_state = "PRE_RENDER"

    # function that is called after rendering finished
    def post_render(self, Scene, unknown_param):

        # reset the operator state to PRE_RENDER
        if self.operator_state != "CANCEL_RENDER": self.operator_state = "POST_RENDER"

    # function that is called when the renderjob is completed
    def completed_render(self, Scene, unknown_param):

        # reset the operator state to COMPLETE_RENDER
        if self.operator_state != "CANCEL_RENDER": self.operator_state = "COMPLETE_RENDER"

    # function that is called if rendering was cancelled
    def cancel_render(self, Scene, unknown_param):

        # set operator state to CANCEL
        self.operator_state = "CANCEL_RENDER"

    # invoke the modal operator
    def invoke(self, context, event):

        # HANDLERS FOR THE RENDERING PROCESS
        # +++++++++++++++++++++++++++++++++++
        bpy.app.handlers.render_init.append(self.init_render)
        bpy.app.handlers.render_pre.append(self.pre_render)
        bpy.app.handlers.render_post.append(self.post_render)
        bpy.app.handlers.render_cancel.append(self.cancel_render)
        bpy.app.handlers.render_complete.append(self.completed_render)

        # HANDLER FOR EVENT TIMER
        # ++++++++++++++++++++++++++++++++++
        # Create timer event that runs every 1 ms to check the rendering process
        self._handle_event_timer = context.window_manager.event_timer_add(0.001, window=context.window)

        # START THE MODAL OPERATOR
        # ++++++++++++++++++++++++++++++++++
        # add the modal operator handler
        context.window_manager.modal_handler_add(self)

        # keep the modal operator running
        return {'RUNNING_MODAL'}



    def modal(self, context, event):

        print("[", self.operator_state, "] WAITING ...")

        # if the TIMER event for the quilt rendering is called
        if event.type == 'TIMER':

            # INVOKE NEW RENDER JOB
            # ++++++++++++++++++++++++++++++++++
            if self.operator_state == "INVOKE_RENDER":

                print("[INFO] Invoking new render job.")

                # start rendering
                # NOTE: Not using write_still because we save the images manually
                result = bpy.ops.render.render('INVOKE_DEFAULT', animation=False)#, write_still=True)

                print("INVOKING RENDER ...", result)


            # runn modal operator
            return {'PASS_THROUGH'}

        else:

            # pass event through
            return {'PASS_THROUGH'}


def register():
    bpy.utils.register_class(LOOKINGGLASS_OT_render_quilt)

if __name__ == "__main__":
    register()
```

Than navigate to the Layout Workspace again. Press F3 and type "render.quilt" and press enter. Then have a look, if a rendering process starts.

> Also, thank you for spending your time on the weekend on trying to fix this. I really appreciate it!

You are welcome! It's a hobby, so I enjoy it - most of the time. ^^

**Comment by JohJakob** [comment]
Yes, it renders one frame!

**Comment by regcs** [comment]
Ok, thanks. You can try the following version. That breaks something else, but the latter should be fixable. But before I go down the road, it would be cool if you would verify that the approach in general works.
[AliceLG-beta7.zip](https://github.com/regcs/AliceLG-beta/files/6619329/AliceLG-beta7.zip)

**Comment by JohJakob** [comment]
Yep, it works now (tried my test scene I sent you)! Blender rendered the views and output the quilt image.

**Comment by regcs** [comment]
Great, thank you for testing!

Just to be sure, since „xzr“ on discord is still experiencing issues: The views in the final quilt are all different and the quilt is displayed correctly on the Portrait?

**Comment by JohJakob** [comment]
I rendered the default 48 view quilt and it is displayed perfectly! Much better than the stretched 45 view quilt I got from blenderLKG

**Comment by regcs** [comment]
Alright, thanks. I was just asking because xzr was getting the same view 48 time.

Then, I think I will mark this here's closed. Thanks for assisting in fixing this.

**Comment by JohJakob** [comment]
Thanks a lot for fixing! 🙌🏻
